INSERT INTO WORKER VALUES(1,5,1,'Operador1');
INSERT INTO WORKER VALUES(2,10,1,'Operador2');
INSERT INTO WORKER VALUES(3,1,1,'Operador3');
INSERT INTO WORKER VALUES(4,5,1,'Operador4');
INSERT INTO WORKER VALUES(5,3,1,'Operador5');
INSERT INTO WORKER VALUES(6,40,2,'Supervisor1');
INSERT INTO WORKER VALUES(7,50,2,'Supervisor2');
INSERT INTO WORKER VALUES(8,10,3,'Director');