INSERT INTO WORKER VALUES(1,0,1,'Operador1');
INSERT INTO WORKER VALUES(2,0,1,'Operador2');
INSERT INTO WORKER VALUES(3,0,1,'Operador3');
INSERT INTO WORKER VALUES(4,0,1,'Operador4');
INSERT INTO WORKER VALUES(5,0,1,'Operador5');
INSERT INTO WORKER VALUES(6,0,2,'Supervisor1');
INSERT INTO WORKER VALUES(7,0,2,'Supervisor2');
INSERT INTO WORKER VALUES(8,0,3,'Director');